/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

/**
 *
 * @author 62838
 */
import backend.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class FormTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        initComponents();
        tampilkanData();
        tampilkanCmbKategori();
        kosongkanForm();
    }

        public void kosongkanForm() {
        IdField.setText("0");
        HargaField.setText("");
        JumlahField.setText("");
        TotalHargaField.setText("");
        JumlahBayarField.setText("");
        KembalianField.setText("");
        TanggalField.setText("");
//        cmbMenu.setSelectedIndex(0);
    }
    public void cariMenu(String keyword){
        ArrayList<Transaksi> list =  new Transaksi().searchMenu(keyword);
        for(Transaksi tr : list){
            HargaField.setText(String.valueOf(tr.getMenu().getHarga()));
            
        }
    }

    public void tampilkanData() {
        String[] kolom = {"ID Transaksi", "Nama Menu", "Harga", "Jumlah", "Total Harga", "Jumlah Bayar", "Jumlah Kembalian", "Tanggal Transaksi"};
        ArrayList<Transaksi> list = new Transaksi().getAll();
        Object rowData[] = new Object[9];

        TableTr.setModel(new DefaultTableModel(new Object[][]{}, kolom));

        for (Transaksi tr : list) {
            rowData[0] = tr.getId_transaksi();
//            rowData[1] = tr.getMenu().getId_menu();
            rowData[1] = tr.getMenu().getNama();
            rowData[2] = tr.getMenu().getHarga();
            rowData[3] = tr.getJumlah();
            rowData[4] = tr.getTotal_harga();
            rowData[5] = tr.getJumlah_bayar();
            rowData[6] = tr.getKembalian();
            rowData[7] = tr.getTanggal();
            
            ((DefaultTableModel) TableTr.getModel()).addRow(rowData);
        }
    }


    public void tampilkanCmbKategori() {
        cmbMenu.setModel(new DefaultComboBoxModel(new Menu().getAll().toArray()));
    }
    public void cari(String keyword) {
        String[] kolom = {"ID Transaksi", "Nama Menu", "Harga", "Jumlah", "Total Harga", "Jumlah Bayar", "Jumlah Kembalian", "Tanggal Transaksi"};
        ArrayList<Transaksi> list = new Transaksi().searchTransaksi(keyword);
        Object rowData[] = new Object[9];

        TableTr.setModel(new DefaultTableModel(new Object[][]{}, kolom));

        for (Transaksi tr : list) {
            rowData[0] = tr.getId_transaksi();
//            rowData[1] = tr.getMenu().getId_menu();
            rowData[1] = tr.getMenu().getNama();
            rowData[2] = tr.getMenu().getHarga();
            rowData[3] = tr.getJumlah();
            rowData[4] = tr.getTotal_harga();
            rowData[5] = tr.getJumlah_bayar();
            rowData[6] = tr.getKembalian();
            rowData[7] = tr.getTanggal();
            
            ((DefaultTableModel) TableTr.getModel()).addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        HargaField = new javax.swing.JTextField();
        JumlahField = new javax.swing.JTextField();
        TotalHargaField = new javax.swing.JTextField();
        JumlahBayarField = new javax.swing.JTextField();
        KembalianField = new javax.swing.JTextField();
        cmbMenu = new javax.swing.JComboBox();
        HitungButton = new javax.swing.JButton();
        SimpanButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTr = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        TanggalField = new javax.swing.JTextField();
        CariButton = new javax.swing.JButton();
        CariField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        TambahButton = new javax.swing.JButton();
        HapusButton = new javax.swing.JButton();
        Hitung2Button = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TRANSAKSI RETRO CAFE");

        jLabel2.setText("Nama Menu");

        jLabel3.setText("Harga");

        jLabel4.setText("Jumlah");

        jLabel5.setText("Total Harga");

        jLabel6.setText("Jumlah Bayar");

        jLabel7.setText("Jumlah Kembalian");

        HargaField.setEditable(false);

        TotalHargaField.setEditable(false);
        TotalHargaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalHargaFieldActionPerformed(evt);
            }
        });

        KembalianField.setEditable(false);

        cmbMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMenuActionPerformed(evt);
            }
        });

        HitungButton.setText("Hitung");
        HitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungButtonActionPerformed(evt);
            }
        });

        SimpanButton.setText("Simpan");
        SimpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanButtonActionPerformed(evt);
            }
        });

        TableTr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableTr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableTrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableTr);

        jLabel8.setText("Tanggal Transaksi");

        CariButton.setText("Cari");
        CariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("ID Transaksi");

        IdField.setEditable(false);
        IdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdFieldActionPerformed(evt);
            }
        });

        TambahButton.setText("Tambah Baru");
        TambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahButtonActionPerformed(evt);
            }
        });

        HapusButton.setText("Hapus");
        HapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusButtonActionPerformed(evt);
            }
        });

        Hitung2Button.setText("Hitung");
        Hitung2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hitung2ButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("FORMAT DD/MM/YYYY");

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(HapusButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(SimpanButton)
                                            .addComponent(jLabel9)
                                            .addComponent(HitungButton)
                                            .addComponent(CariButton)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jButton1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CariField, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cmbMenu, 0, 112, Short.MAX_VALUE)
                                                    .addComponent(HargaField)
                                                    .addComponent(JumlahField)
                                                    .addComponent(TotalHargaField)
                                                    .addComponent(IdField))
                                                .addGap(78, 78, 78)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Hitung2Button)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(TanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel10))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel7)
                                                            .addComponent(jLabel6))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(JumlahBayarField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(KembalianField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(TambahButton)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(217, 217, 217)
                                        .addComponent(jLabel1)))))
                        .addGap(0, 151, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JumlahBayarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(KembalianField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(TanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Hitung2Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TotalHargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(JumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(HitungButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanButton)
                    .addComponent(TambahButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CariButton)
                    .addComponent(CariField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HapusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanButtonActionPerformed
        // TODO add your handling code here:
        Transaksi tr = new Transaksi();
        tr.setId_transaksi(Integer.parseInt(IdField.getText()));
        tr.setMenu((Menu) cmbMenu.getSelectedItem());        
        tr.getMenu().setHarga(Integer.parseInt(JumlahField.getText()));
        tr.setJumlah(Integer.parseInt(JumlahField.getText()));
        tr.setTotal_harga(Integer.parseInt(TotalHargaField.getText()));
        tr.setJumlah_bayar(Integer.parseInt(JumlahBayarField.getText()));
        tr.setKembalian(Integer.parseInt(KembalianField.getText()));
        tr.setTanggal(TanggalField.getText());
        tr.save();
        IdField.setText(Integer.toString(tr.getId_transaksi()));
        tampilkanData();
    }//GEN-LAST:event_SimpanButtonActionPerformed

    private void TotalHargaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalHargaFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TotalHargaFieldActionPerformed

    private void HitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungButtonActionPerformed
        // TODO add your handling code here:
        
        int jumlah = Integer.parseInt(JumlahField.getText());
        int harga = Integer.parseInt(HargaField.getText());
        int total_harga = jumlah * harga;
        TotalHargaField.setText(String.valueOf(total_harga));
        
    }//GEN-LAST:event_HitungButtonActionPerformed

    private void TambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahButtonActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_TambahButtonActionPerformed

    private void CariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariButtonActionPerformed
        // TODO add your handling code here:
        cari(CariField.getText());
    }//GEN-LAST:event_CariButtonActionPerformed

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableTr.getModel();
        int row = TableTr.getSelectedRow();

        Transaksi tr = new Transaksi().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        tr.delete();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_HapusButtonActionPerformed

    private void cmbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMenuActionPerformed
        // TODO add your handling code here:
        cariMenu(cmbMenu.getSelectedItem().toString());
    }//GEN-LAST:event_cmbMenuActionPerformed

    private void TableTrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableTrMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableTr.getModel();
        int row = TableTr.getSelectedRow();
        Transaksi tr = new Transaksi();
        
        tr = tr.getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        
        IdField.setText(String.valueOf(tr.getId_transaksi()));
        cmbMenu.getModel().setSelectedItem(tr.getMenu());
        HargaField.setText(String.valueOf(tr.getMenu().getHarga()));
        JumlahField.setText(String.valueOf(tr.getJumlah()));
        TotalHargaField.setText(String.valueOf(tr.getTotal_harga()));
        JumlahBayarField.setText(String.valueOf(tr.getJumlah_bayar()));
        JumlahBayarField.setEditable(false);
        KembalianField.setText(String.valueOf(tr.getKembalian()));
        TanggalField.setText(String.valueOf(tr.getTanggal()));
        
    }//GEN-LAST:event_TableTrMouseClicked

    private void Hitung2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hitung2ButtonActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(TotalHargaField.getText());
        int bayar = Integer.parseInt(JumlahBayarField.getText());
        int kembalian = bayar - jumlah;
        KembalianField.setText(String.valueOf(kembalian));
        
    }//GEN-LAST:event_Hitung2ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FormMain().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CariButton;
    private javax.swing.JTextField CariField;
    private javax.swing.JButton HapusButton;
    private javax.swing.JTextField HargaField;
    private javax.swing.JButton Hitung2Button;
    private javax.swing.JButton HitungButton;
    private javax.swing.JTextField IdField;
    private javax.swing.JTextField JumlahBayarField;
    private javax.swing.JTextField JumlahField;
    private javax.swing.JTextField KembalianField;
    private javax.swing.JButton SimpanButton;
    private javax.swing.JTable TableTr;
    private javax.swing.JButton TambahButton;
    private javax.swing.JTextField TanggalField;
    private javax.swing.JTextField TotalHargaField;
    private javax.swing.JComboBox cmbMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
